{{- if or .Values.auth.basicAuth.password .Values.auth.bearerToken.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-gpu-lens.secretName" . }}
  labels:
    {{- include "ai-gpu-lens.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.basicAuth.password }}
  {{ .Values.auth.basicAuth.existingSecretKey }}: {{ .Values.auth.basicAuth.password | quote }}
  {{- end }}
  {{- if .Values.auth.bearerToken.token }}
  {{ .Values.auth.bearerToken.existingSecretKey }}: {{ .Values.auth.bearerToken.token | quote }}
  {{- end }}
{{- end }}
