from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .prometheus import (
    DEFAULT_GPU_UTIL_QUERY,
    DEFAULT_KUBE_GPU_REQUEST_QUERY,
    DEFAULT_MEMORY_TOTAL_FALLBACK_QUERY,
    DEFAULT_MEMORY_TOTAL_QUERY,
    DEFAULT_MEMORY_USED_QUERY,
)


DEFAULT_DASHBOARD_UID = "ai-gpu-lens"
DEFAULT_DASHBOARD_TITLE = "ai-gpu-lens GPU Fleet"
DEFAULT_DATASOURCE_UID = "${DS_PROMETHEUS}"
DEFAULT_MEMORY_TOTAL_OR_FALLBACK_QUERY = (
    f"{DEFAULT_MEMORY_TOTAL_QUERY} or ({DEFAULT_MEMORY_TOTAL_FALLBACK_QUERY})"
)


def write_dashboard_json(dashboard: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(dashboard, indent=2) + "\n", encoding="utf-8")


def build_grafana_dashboard(
    *,
    title: str = DEFAULT_DASHBOARD_TITLE,
    uid: str = DEFAULT_DASHBOARD_UID,
    datasource_uid: str = DEFAULT_DATASOURCE_UID,
    gpu_util_query: str = DEFAULT_GPU_UTIL_QUERY,
    memory_used_query: str = DEFAULT_MEMORY_USED_QUERY,
    memory_total_query: str = DEFAULT_MEMORY_TOTAL_OR_FALLBACK_QUERY,
    kube_gpu_request_query: str | None = DEFAULT_KUBE_GPU_REQUEST_QUERY,
    time_from: str = "now-24h",
    refresh: str = "1m",
) -> dict[str, Any]:
    datasource = prometheus_datasource(datasource_uid)
    dashboard = {
        "__inputs": datasource_inputs(datasource_uid),
        "__requires": [
            {"type": "grafana", "id": "grafana", "name": "Grafana", "version": ""},
            {
                "type": "datasource",
                "id": "prometheus",
                "name": "Prometheus",
                "version": "",
            },
            {
                "type": "panel",
                "id": "stat",
                "name": "Stat",
                "version": "",
            },
            {
                "type": "panel",
                "id": "timeseries",
                "name": "Time series",
                "version": "",
            },
            {
                "type": "panel",
                "id": "table",
                "name": "Table",
                "version": "",
            },
        ],
        "annotations": {"list": []},
        "editable": True,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 1,
        "id": None,
        "links": [],
        "liveNow": False,
        "panels": build_panels(
            datasource=datasource,
            gpu_util_query=gpu_util_query,
            memory_used_query=memory_used_query,
            memory_total_query=memory_total_query,
            kube_gpu_request_query=kube_gpu_request_query,
        ),
        "refresh": refresh,
        "schemaVersion": 39,
        "tags": ["ai-gpu-lens", "gpu", "kubernetes", "finops"],
        "templating": {
            "list": build_variables(datasource, gpu_util_query),
        },
        "time": {"from": time_from, "to": "now"},
        "timepicker": {
            "refresh_intervals": ["30s", "1m", "5m", "15m", "30m", "1h"],
        },
        "timezone": "browser",
        "title": title,
        "uid": uid,
        "version": 1,
        "weekStart": "",
        "description": (
            "Generated by ai-gpu-lens. Import this dashboard into Grafana and "
            "select a Prometheus datasource that exposes DCGM exporter metrics."
        ),
        "aiGpuLens": {
            "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "gpuUtilQuery": gpu_util_query,
            "memoryUsedQuery": memory_used_query,
            "memoryTotalQuery": memory_total_query,
            "kubeGpuRequestQuery": kube_gpu_request_query,
        },
    }
    return dashboard


def datasource_inputs(datasource_uid: str) -> list[dict[str, str]]:
    if datasource_uid != DEFAULT_DATASOURCE_UID:
        return []
    return [
        {
            "name": "DS_PROMETHEUS",
            "label": "Prometheus",
            "description": "Prometheus datasource with DCGM exporter metrics",
            "type": "datasource",
            "pluginId": "prometheus",
            "pluginName": "Prometheus",
        }
    ]


def prometheus_datasource(uid: str) -> dict[str, str]:
    return {"type": "prometheus", "uid": uid}


def build_variables(
    datasource: dict[str, str],
    gpu_util_query: str,
) -> list[dict[str, Any]]:
    return [
        query_variable(
            "node",
            "Node",
            f"label_values({gpu_util_query}, Hostname)",
            datasource,
        ),
        query_variable(
            "namespace",
            "Namespace",
            f"label_values({gpu_util_query}, namespace)",
            datasource,
        ),
        query_variable(
            "model",
            "GPU model",
            f"label_values({gpu_util_query}, modelName)",
            datasource,
        ),
    ]


def query_variable(
    name: str,
    label: str,
    query: str,
    datasource: dict[str, str],
) -> dict[str, Any]:
    return {
        "allValue": ".*",
        "current": {"selected": True, "text": "All", "value": "$__all"},
        "datasource": datasource,
        "definition": query,
        "hide": 0,
        "includeAll": True,
        "label": label,
        "multi": True,
        "name": name,
        "options": [],
        "query": query,
        "refresh": 1,
        "regex": "",
        "skipUrlSync": False,
        "sort": 1,
        "type": "query",
    }


def build_panels(
    *,
    datasource: dict[str, str],
    gpu_util_query: str,
    memory_used_query: str,
    memory_total_query: str,
    kube_gpu_request_query: str | None,
) -> list[dict[str, Any]]:
    gpu_filter = 'Hostname=~"$node", namespace=~"$namespace", modelName=~"$model"'
    filtered_gpu_query = with_metric_filter(gpu_util_query, gpu_filter)
    memory_percent_query = (
        f"100 * ({memory_used_query}) / ignoring(__name__) ({memory_total_query})"
    )

    panels = [
        stat_panel(
            1,
            "Fleet average GPU utilization",
            "avg",
            f"avg({filtered_gpu_query})",
            datasource,
            0,
            0,
            unit="percent",
        ),
        stat_panel(
            2,
            "GPU series",
            "count",
            f"count({filtered_gpu_query})",
            datasource,
            6,
            0,
            unit="short",
        ),
        stat_panel(
            3,
            "Idle GPUs",
            "idle",
            f"sum(avg_over_time(({filtered_gpu_query})[$__rate_interval:]) < bool 5)",
            datasource,
            12,
            0,
            unit="short",
        ),
        stat_panel(
            4,
            "Framebuffer memory coverage",
            "memory",
            f"count({memory_used_query})",
            datasource,
            18,
            0,
            unit="short",
        ),
        timeseries_panel(
            5,
            "Fleet GPU utilization",
            "avg utilization",
            f"avg({filtered_gpu_query})",
            datasource,
            0,
            4,
            unit="percent",
        ),
        timeseries_panel(
            6,
            "GPU utilization by device",
            "{{Hostname}} {{modelName}} {{UUID}}",
            f"avg by (Hostname, UUID, modelName) ({filtered_gpu_query})",
            datasource,
            12,
            4,
            unit="percent",
        ),
        timeseries_panel(
            7,
            "Framebuffer memory used",
            "{{Hostname}} {{modelName}} {{UUID}}",
            f"avg by (Hostname, UUID, modelName) ({memory_percent_query})",
            datasource,
            0,
            12,
            unit="percent",
        ),
        table_panel(
            8,
            "Lowest average utilization in selected range",
            "avg util",
            (
                "sort(avg by (Hostname, UUID, modelName, namespace, pod) "
                f"(avg_over_time(({filtered_gpu_query})[$__range:])))"
            ),
            datasource,
            12,
            12,
            unit="percent",
        ),
        timeseries_multi_panel(
            9,
            "Metric coverage",
            [
                ("A", f"count({gpu_util_query})", "gpu_utilization"),
                ("B", f"count({memory_used_query})", "memory_used"),
                ("C", f"count({memory_total_query})", "memory_total"),
            ],
            datasource,
            0,
            20,
            unit="short",
        ),
    ]
    if kube_gpu_request_query:
        panels.extend(
            [
                stat_panel(
                    10,
                    "Requested GPUs",
                    "requested",
                    f"sum({kube_gpu_request_query})",
                    datasource,
                    18,
                    20,
                    unit="short",
                ),
                timeseries_panel(
                    11,
                    "Requested GPUs by namespace",
                    "{{namespace}}",
                    f"sum by (namespace) ({kube_gpu_request_query})",
                    datasource,
                    0,
                    24,
                    unit="short",
                ),
                table_panel(
                    12,
                    "Requested GPUs by workload",
                    "requested",
                    f"sort_desc(sum by (namespace, pod) ({kube_gpu_request_query}))",
                    datasource,
                    12,
                    24,
                    unit="short",
                ),
            ]
        )
    return panels


def with_metric_filter(query: str, label_filter: str) -> str:
    if is_simple_metric_name(query):
        return f"{query}{{{label_filter}}}"
    return query


def is_simple_metric_name(query: str) -> bool:
    return query.replace("_", "").replace(":", "").isalnum()


def stat_panel(
    panel_id: int,
    title: str,
    ref_name: str,
    expr: str,
    datasource: dict[str, str],
    x: int,
    y: int,
    *,
    unit: str,
) -> dict[str, Any]:
    return {
        "id": panel_id,
        "type": "stat",
        "title": title,
        "datasource": datasource,
        "gridPos": {"h": 4, "w": 6, "x": x, "y": y},
        "targets": [target("A", expr, ref_name, datasource, instant=True)],
        "fieldConfig": field_config(unit),
        "options": {
            "colorMode": "value",
            "graphMode": "area",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
                "calcs": ["lastNotNull"],
                "fields": "",
                "values": False,
            },
            "textMode": "auto",
        },
    }


def timeseries_panel(
    panel_id: int,
    title: str,
    legend: str,
    expr: str,
    datasource: dict[str, str],
    x: int,
    y: int,
    *,
    unit: str,
) -> dict[str, Any]:
    return {
        "id": panel_id,
        "type": "timeseries",
        "title": title,
        "datasource": datasource,
        "gridPos": {"h": 8, "w": 12, "x": x, "y": y},
        "targets": [target("A", expr, legend, datasource)],
        "fieldConfig": field_config(unit),
        "options": {
            "legend": {
                "calcs": ["lastNotNull", "mean"],
                "displayMode": "table",
                "placement": "bottom",
                "showLegend": True,
            },
            "tooltip": {"mode": "multi", "sort": "desc"},
        },
    }


def timeseries_multi_panel(
    panel_id: int,
    title: str,
    targets: list[tuple[str, str, str]],
    datasource: dict[str, str],
    x: int,
    y: int,
    *,
    unit: str,
) -> dict[str, Any]:
    panel = timeseries_panel(
        panel_id,
        title,
        targets[0][2],
        targets[0][1],
        datasource,
        x,
        y,
        unit=unit,
    )
    panel["targets"] = [
        target(ref_id, expr, legend, datasource)
        for ref_id, expr, legend in targets
    ]
    return panel


def table_panel(
    panel_id: int,
    title: str,
    legend: str,
    expr: str,
    datasource: dict[str, str],
    x: int,
    y: int,
    *,
    unit: str,
) -> dict[str, Any]:
    return {
        "id": panel_id,
        "type": "table",
        "title": title,
        "datasource": datasource,
        "gridPos": {"h": 8, "w": 12, "x": x, "y": y},
        "targets": [target("A", expr, legend, datasource, instant=True)],
        "fieldConfig": field_config(unit),
        "options": {
            "showHeader": True,
            "sortBy": [{"desc": False, "displayName": "Value"}],
        },
    }


def field_config(unit: str) -> dict[str, Any]:
    return {
        "defaults": {
            "color": {"mode": "palette-classic"},
            "custom": {
                "axisCenteredZero": False,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 12,
                "gradientMode": "none",
                "hideFrom": {
                    "legend": False,
                    "tooltip": False,
                    "viz": False,
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {"type": "linear"},
                "showPoints": "never",
                "spanNulls": False,
                "stacking": {"group": "A", "mode": "none"},
                "thresholdsStyle": {"mode": "off"},
            },
            "decimals": 2,
            "mappings": [],
            "thresholds": {
                "mode": "absolute",
                "steps": [
                    {"color": "green", "value": None},
                    {"color": "orange", "value": 70},
                    {"color": "red", "value": 90},
                ],
            },
            "unit": unit,
        },
        "overrides": [],
    }


def target(
    ref_id: str,
    expr: str,
    legend: str,
    datasource: dict[str, str],
    *,
    instant: bool = False,
) -> dict[str, Any]:
    return {
        "datasource": datasource,
        "editorMode": "code",
        "expr": expr,
        "format": "time_series",
        "hide": False,
        "instant": instant,
        "legendFormat": legend,
        "range": not instant,
        "refId": ref_id,
    }
